### ISSUE TITLE
没有网络的时候开屏广告会卡住无法跳过

### ISSUE THREAD

**Issue by jlcool** [hetian9288/flutter_gdt_plugin#2]
可能不是这个插件的问题，但是有什么建议可以帮助下我吗

**Comment by jlcool** [comment]
暂时在onNoAD中添加以下代码
`if (layout != null) {
            ViewGroup vg = (ViewGroup) layout.getParent();
            vg.removeView(layout);
            layout = null;
            splashAD = null;
        }
        _Splash = null;`

**Comment by hetian9288** [comment]
没有广告的时候销毁广告，很久没同步代码了
